spring.application.name=backend

# H2データベースの保存先
spring.datasource.url=jdbc:h2:file:./data/missiondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JavaのEntityをもとにDBのテーブルを更新する
spring.jpa.hibernate.ddl-auto=update

# 実行されたSQLをログへ表示する
spring.jpa.show-sql=true

# ブラウザからH2の中身を確認できるようにする
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console